### ISSUE TITLE
Bot Embed keywords don't work

### ISSUE THREAD

**Issue by UltraSyko** [sarahkittyy/KeywordTracker#16]
![DiscordCanary_h5NBk6dn6R](https://user-images.githubusercontent.com/16283463/130305783-0892c0d2-b398-4829-878b-2a79a0951265.png)
![DiscordCanary_BqpacLV9KI](https://user-images.githubusercontent.com/16283463/130305785-f855940a-408a-4c18-b07a-07fb4c3d81d1.png)
![Discord_xvjhlgO1Gz](https://user-images.githubusercontent.com/16283463/130305789-f9a70dc3-0404-4a30-9910-19e286e29cd4.png)

**Comment by fabio80mi** [comment]
First of all thank you for doing this.
I actually discovered BetterDiscord for this notification feature and unfortunately the text i am trying to get notified on are not working on the plugin as it is now as likely they are coming from a bot.
So +1 on this request and once again thank you for your time in creating this plugin!

**Comment by sarahkittyy** [comment]
@fabio80mi @UltraSyko it's in the next update. you can pull the source from here to get it early or wait for betterdiscord to approve the new version

**Comment by UltraSyko** [comment]
I did see it! Thanks a bunch
