### ISSUE TITLE
Feature request: Guild/channel mass toggle

### ISSUE THREAD

**Issue by XenonUnity** [sarahkittyy/KeywordTracker#2]
A feature that I think would be helpful is a toggle switch that enables/disables all guilds or channels from being tracked. I'm currently in 122 servers and going through them all to disable the ones I don't want to be tracked is a little tedious so having a toggle to disable them all and go through the ones I want would be awesome :)

**Comment by sarahkittyy** [comment]
Added in 1a7502b5092745538774a1eb07d7c44a015be775 :)

Be careful with it though, it'll completely enable / disable _every_ channel / guild
