### ISSUE TITLE
Plugin is set to always send desktop notifications regardless of Discord's own setting

### ISSUE THREAD

**Issue by drjaska** [sarahkittyy/KeywordTracker#28]
In Discord under App Settings>Notifications there is an option which disables or enables desktop pop-up notifications for notifications. KeywordTracker plugin doesn't respect that setting in Discord nor does the plugin have an off-switch for desktop notifications in plugin's own settings.

I'd wish for the plugin to follow the Discord's main setting but if reading its state is impossible a seperate off-switch would be completely acceptable too.

This is a very annoying issue for me as any desktop notifications cause issues for my Linux's window manager and any desktop pop-up notifications cause fullscreen SDL applications such as games to suffer from very severe stuttering and a big drop in FPS for the duration of the notification's display time.

**Comment by sarahkittyy** [comment]
I believe it should respect DND now. You can turn off the sound of the notifications in the settings

**Comment by drjaska** [comment]
> I believe it should respect DND now.

While this is a great improvement it nor turning of sound alone was the point of this issue. Please re-open this.
