### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by SexyNippleKiller** [sarahkittyy/KeywordTracker#3]
Hi. in the app settings you write "One regex per line" and I'm guessing you mean "one word/sentence per line", but I'm really not quite sure. So would be nice if you could edit the in-app settings text to be more understandable, and clarify what you mean

**Comment by sarahkittyy** [comment]
Words and phrases work too, i.e
```
sarah
kitty
```
would match any phrase with either sarah or kitty in it.

Regexes are for more advanced users, surrounded by `/`'s, so you can match more advanced things, i.e.
```
/sa[rw]ah/i
```
would match sawah, or sarah, without caring about capitalization.

I do want to revamp descriptions and clarify things and that will come soon <3

**Comment by sarahkittyy** [comment]
Fixed in 1a7502b5092745538774a1eb07d7c44a015be775
