### ISSUE TITLE
No longer working on new version?

### ISSUE THREAD

**Issue by ImDini** [sarahkittyy/KeywordTracker#31]
The button doesn't exist anymore and it's enabled

**Comment by Kuuuube** [comment]
Got this same issue. It appears to be caused by something on initial startup of discord. Disabling and enabling that plugin then flipping through a few servers got the button back for me on that instance of discord.

**Comment by ImDini** [comment]
> Got this same issue. It appears to be caused by something on initial startup of discord. Disabling and enabling that plugin then flipping through a few servers got the button back for me on that instance of discord.

Yeah this as well as it still "works" I still get notifications just no where to open them in app unless I click the windows notification it gives.

**Comment by sarahkittyy** [comment]
Fixed in e08037! :)
