### ISSUE TITLE
Notifications broken on v1.2.5

### ISSUE THREAD

**Issue by Kuuuube** [sarahkittyy/KeywordTracker#32]
This does not seem to be the same issue as #30 since I am not getting any of those errors but notifications just refuse to work. 

After reverting to v1.2.4 everything seems to work as intended so it appears to be something caused by v1.2.5.

**Comment by nosut** [comment]
Same problem here. No longer working.

**Comment by Kuuuube** [comment]
Reverting to v1.2.4 seems to be broken now as well. I'm also not getting this issue anymore, only #31. 

I'll leave the issue open since I wasn't the only one to have this issue even though it doesn't appear to be an issue anymore.

**Comment by sarahkittyy** [comment]
The issue with the button being gone has been fixed in e08037cab595abbd15fb01e79dd7317e335c8019.

As for the notifications please open a separate issue if they continue to happen after you update to v1.2.6
