### ISSUE TITLE
Unreliable loading and breakages

### ISSUE THREAD

**Issue by Kuuuube** [sarahkittyy/KeywordTracker#33]
I'd noticed that sometimes KeywordTracker doesn't pick up on keywords. I think I've narrowed it down now.

Upon launch of discord if KeywordTracker was already enabled it will load in properly and keywords will work properly and send notifications properly. After launch if KeywordTracker is disabled and enabled it will still send notifications until you tab out of discord, flip through settings pages a few times, flip through a few servers, a few channels, etc. (Triggering it is a but unreliable and it won't happen doing one of those things once always but just screwing around with it a bit doing those things I got the bug every time one way or another.) Then the notifications break entirely and don't come back until the plugin is disabled and enabled again at which point the issue repeats itself.

This also leads to the plugin breaking every time it is updated in the discord instance that it was updated in if the user had KeywordTracker enabled on startup. (This is what caused me to think v1.2.5 notifications were entirely broken in #32 but later it mysteriously fixed itself.)

Having KeywordTracker disabled and only enabling KeywordTracker after startup doesn't seem to have this issue from my testing.

Hopefully this is enough info to replicate the issue on your end. 

Obvious workaround for anyone who gets this bug and sees this issue is to just leave KeywordTracker enabled on startup and if you mess with it or update it restart discord.

**Comment by sarahkittyy** [comment]
Open a new issue if this is still broken
