### ISSUE TITLE
No inbox button, no notifications, no error

### ISSUE THREAD

**Issue by hkrawczyk** [sarahkittyy/KeywordTracker#34]
Installed version 1.2.6 and I would like to enable notifications for ALL messages from a specific user.

those are my plugins
![a1](https://user-images.githubusercontent.com/9109785/148383374-3810ce74-6bfe-4db6-85ed-233fbee83bda.png)

I leave empty field in regexp
![a2](https://user-images.githubusercontent.com/9109785/148383409-06c1541f-96ea-479d-9d0a-272714b99256.png)

and then select my server but i don't know what position is ON and what OFF as its weirdly annotated in the message above
![a3](https://user-images.githubusercontent.com/9109785/148383464-b0252a13-7af7-462c-8981-a202d3da19cd.png)

and put my id in whitelist to get notifications
![a4](https://user-images.githubusercontent.com/9109785/148384455-bbaecc46-1135-48d7-b19e-cbcf73c33401.png)

sadly I don't get any inbox icon (where should I even look at it?), nor i get notifications or even error. 
Can I kindly ask for help here?

I've downgraded to 1.2.1 and still couldn't see inbox. 
Later on I've upgraded to 1.2.6 but still without any success.

Few questions:
1. what position slider should be to enable setting (left or right)?
2. do I fill it correctly?
3. is it tested with a specific discord version?
4. if I add my DEV ID, will the notifications work? (notify me about all my messages) or will it work only for other users?
5. where inbox icons should appear?
6. not all channels are displayed in the list, nor all threads. Will the plugin work with all threads if I mark the channel? Is there any way to find rest of the channels?

I'd really love to get this working and I'll be happy to buy you a few cups of coffee for devs if you will be able to solve it :)

@sarahkittyy

**Comment by hkrawczyk** [comment]
what positon slider should be to enable setting (left or right)?

**Comment by sarahkittyy** [comment]
See if this issue still occurs on the latest version @hkrawczyk (v1.3.0, either download it from this repo or wait for the update to be pushed through BD)
