### ISSUE TITLE
inbox button doesn't work when language is not English

### ISSUE THREAD

**Issue by SoftwareSing** [sarahkittyy/KeywordTracker#35]
![image](https://user-images.githubusercontent.com/36272700/150653531-35676cb8-8c09-4521-8d6d-8c6de0df4a14.png)

pinned messages button's `aria-label` is different in every language.  
In English is `Pinned Messages` , in Chinese is `已釘選的訊息`.

---

```js
buildInboxPanel() {
  let pinned = ['Pinned Messages', '已釘選的訊息']
    .map((ariaLabelText) => document.querySelector(`div[aria-label*="${ariaLabelText}" i]`))
    .find((pinned) => pinned);
  if (!pinned) {
    return;
  }
```

This works for me, but need more text to complete fix it for every language user.

---

I didn't know there's an unread inbox until I discovered my config file is grown to 28MB, so many unread messages, lol

**Comment by sarahkittyy** [comment]
Fixed in 992959e9732acf79b9b66a00c289c61809477b5b (v1.3.0) :)
