### ISSUE TITLE
Cant open configuration window, haven't gotten any notifications.

### ISSUE THREAD

**Issue by Ingvaarr** [sarahkittyy/KeywordTracker#36]
I think a recent ZLib update might have broken smth.

**Comment by TheHunter1234** [comment]
I am getting the same too.
Discord stable with plugin version 1.2.6

**Comment by Ceebly** [comment]
DiscordAPI was removed from ZLib, now the plugin can't access the guilds anymore. Tried fixing it, but I don't know enough about the lib / js in general.

**Comment by bfaceface** [comment]
Won't be updated anymore?

**Comment by sarahkittyy** [comment]
Forgive me everyone!! I was on vacation. I just got home. Give me a few minutes :)

**Comment by sarahkittyy** [comment]
Fixed in 992959e9732acf79b9b66a00c289c61809477b5b (v1.3.0)
