### ISSUE TITLE
[BUG] - Self testing does not work.

### ISSUE THREAD

**Issue by BigFlubba** [sarahkittyy/KeywordTracker#39]
I have been trying to make sure the plugin works properly and when I do self-testing it will not trigger. I am convinced that the plugin does not work at all. I am using the latest update with the toggle enabled for self-testing.

**Comment by sarahkittyy** [comment]
It does not work in dms, you should be sure your keyword is correct, and be sure to enable the channels / servers you use it in :)

**Comment by BigFlubba** [comment]
I was testing it in a server, my keywords are correct, and channels and servers are enabled.

**Comment by sarahkittyy** [comment]
Do you have the dependency, ZLib, installed?

**Comment by sarahkittyy** [comment]
Show me your keywords and what you're sending and all that, the more info the better.

**Comment by BigFlubba** [comment]
![image](https://user-images.githubusercontent.com/69104450/151644474-a08c4dbc-fb6b-47b0-8fde-5266c5831426.png)
![image](https://user-images.githubusercontent.com/69104450/151644475-b179a8fe-c3de-477a-83e3-7dc0a64d44ad.png)
![image](https://user-images.githubusercontent.com/69104450/151644476-341e571c-0355-43e6-8491-49d29365389a.png)
![image](https://user-images.githubusercontent.com/69104450/151644477-c82c3d81-43b8-4d66-80b6-8ef71b11fe2a.png)
![image](https://user-images.githubusercontent.com/69104450/151644479-07468711-2ea7-492a-b24e-0f473fcbd32b.png)
![image](https://user-images.githubusercontent.com/69104450/151644481-9547ff33-decc-4f79-8cdb-e7f1442e09c2.png)
![image](https://user-images.githubusercontent.com/69104450/151644493-8888eb96-b8b8-464d-8071-d79bde0ef278.png)

**Comment by BigFlubba** [comment]
Those are all the keywords I can show because the rest is personal information (my name and such).

**Comment by sarahkittyy** [comment]
i'm sure there's something wrong with your regex
try something simple

**Comment by BigFlubba** [comment]
Same issue.

**Comment by BigFlubba** [comment]
I also see no errors or anything from that plugin in the console.

**Comment by BigFlubba** [comment]
It looks like it is functioning normally but nothing in the inbox.

**Comment by BigFlubba** [comment]
So this was weird. I went and deleted the plugin, config file, closed discord, reinstalled it, and launched discord and it works perfectly. I have no idea how or why it wasn't notifying or anything, but it works now. Thanks for trying to help.
