### ISSUE TITLE
Feature Request: match history/log

### ISSUE THREAD

**Issue by jhkl33** [sarahkittyy/KeywordTracker#4]
Hi! 

It would be much appreciated if you could add some sort of log or history with an overview of past matches. I get random pings but sometimes I don't get a desktop notification (if you disable desktop notifications you get nothing but the ping sound), and I have no idea which keyword or server triggered it. Searching and checking every one would be pain, so a simple log with timestamps would make it a lot easier.

Cheers, love the work you've done!

**Comment by sarahkittyy** [comment]
Duplicate of #1, this is on my to-do list :)
