### ISSUE TITLE
Channels not visible on light theme

### ISSUE THREAD

**Issue by Lesko987** [sarahkittyy/KeywordTracker#41]
It seems that channel names are written with white on white background on the Light discord theme.

Aleš

**Comment by sarahkittyy** [comment]
This is definitely, 1000%, *not* a KeywordTracker issue, unless you can show me otherwise.

**Comment by Lesko987** [comment]
I think it is KeywordTracker problem. 
In KeywordTracker.plugin.js on line 670 you set text color to white.

              channelSwitchText.style['color'] = 'white';

I have no idea on how to use the theme colors, but this way it is impossible to define the channels.

Aleš
