### ISSUE TITLE
Feature idea: per channel/per server/per user keywords

### ISSUE THREAD

**Issue by ArcWandx** [sarahkittyy/KeywordTracker#42]
idek how that'd work, but if you can figure it out, that'd be actually insane

**Comment by BiffBish** [comment]
Sounds like a cool idea. I might make a pull request with that feature

**Comment by sarahkittyy** [comment]
Added exactly that in 3a400339c5b2c4bd04b3b5085e6ecadc49bf6f67
![288406662-de24b333-1a80-44f8-8f20-fa0fc242d2dd](https://github.com/sarahkittyy/KeywordTracker/assets/31551546/9874edd2-f5be-4eeb-aa18-7a7312552d2e)
