### ISSUE TITLE
Settings don't open

### ISSUE THREAD

**Issue by damian101** [sarahkittyy/KeywordTracker#44]
When clicking on the Settings symbol, I only get message "Could not open settings for KeywordTracker". Which makes the plugin useless for me since I can't add keywords. Worked a few months ago. I use standard Discord on Arch Linux.

**Comment by sarahkittyy** [comment]
Do you have the dependency? https://betterdiscord.app/plugin/ZeresPluginLibrary

**Comment by sarahkittyy** [comment]
See if the newest update fixes your issue @damian101.

**Comment by damian101** [comment]
> See if the newest update fixes your issue @damian101.

fixed :)
