### ISSUE TITLE
Notification doesn't direct to the server and channel ( ver. latest update but I don't believe it started with the update ) 

### ISSUE THREAD

**Issue by dullus0000** [sarahkittyy/KeywordTracker#47]
Has anyone experience this? where when I click the notifications, it opens discord ( when I'm tabbed out ) but doesn't direct me to the actual message, instead it just stays on the previous channel that I left it in. 

I've tried everything at this point. Reset settings, uninstall BD and discord, cleared plugins and configs, but nothing works, i've been looking at my windows settings but I don't believe it's that since normal ( All messages, mentions, etc. )notifications from discord works just fine.

edit: interestingly, the new keyword matches tab next to the pin button actually works... (if that changes anything?)

This might be a just me issue but if anyone experienced it before, lmk pls.  
Thank you.

**Comment by ImDini** [comment]
Yeah I came to report as well. You can no longer click the notification to go where the keyword occurs. I always have to open the keyword match menu to go to the message

**Comment by dullus0000** [comment]
Anyone know any fix? doesn't seem like reverting previous versions does anything.

**Comment by dullus0000** [comment]
Anyone know any fix for this? I've tried loading some of the previous versions that I think the notifications work but they somehow doesn't work anymore (no notif at all).

**Comment by sarahkittyy** [comment]
ahhh stop being correct, all of you
i'll work on it rn

**Comment by dullus0000** [comment]
> ahhh stop being correct, all of you i'll work on it rn

Sorry for the bother hehe. The plugin is just so useful lol, i depend on it alot now lol. And THANKS very much for the plugin and the fix!!

**Comment by TheIvanPro** [comment]
I think the same, thank you so much!

**Comment by sarahkittyy** [comment]
Fixed in latest update :)
