### ISSUE TITLE
List of User ids to ignore

### ISSUE THREAD

**Issue by tipakA** [sarahkittyy/KeywordTracker#5]
Hello, since this seems to be replacement for old WordNotifications plugin, it seems to be lacking way to ignore certain users. (Old plugin also accepted channel ids, but there is a separate option for that here)

No clue if that's on your to-do list yet, but it would be nice to ignore some bots from highlighting me in some tags :)

<hr>

Also, sorry for pushing that into that issue, but now that i look at it, the notification sound is forced. Might be an edge case, but IMO a switch wouldn't hurt anyone

**Comment by sarahkittyy** [comment]
Added in b57b52dbc56a2b5bd6768b494bd8d1e6ac9f3495 :)

Thanks for using my plugin!
