### ISSUE TITLE
PlugIn not working

### ISSUE THREAD

**Issue by TheGESH** [sarahkittyy/KeywordTracker#50]
Hi, I just installed the plugin and am trying to get notifications on specific keywords. It seems like the plugin i snot working for me. Or may be I am doing something wrong? Here are some screemshots of Version, Settings etc.
![image](https://user-images.githubusercontent.com/103202087/162228240-38959c8c-12b1-43f4-bd90-a3ccdf2fa1cd.png)
![image](https://user-images.githubusercontent.com/103202087/162228271-7342d2cf-cf6c-4ab9-8b01-ed9cfee5d18b.png)
![image](https://user-images.githubusercontent.com/103202087/162228316-acff6058-4996-4d14-8e0a-d1cd0c51d6eb.png)
![image](https://user-images.githubusercontent.com/103202087/162228403-5ae3425a-2748-4360-bb2b-ad1d3ffa9d7d.png)
![image](https://user-images.githubusercontent.com/103202087/162228537-c4e86358-69bf-4ff6-a07b-cd6b1f8f2d01.png)

**Comment by Organizer21** [comment]
Did you ever get this resolved? Having the exact same issue, except for my entries being /xxxxxx/i regex syntax. Not seeing any notifications even if there's been references with my "words".
