### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by CovetingEpiphany2152** [sarahkittyy/KeywordTracker#52]
This error seems to be popping up non-stop for me.

![image](https://user-images.githubusercontent.com/7296340/164953537-b71b46a2-8c02-4381-95a2-96da587787f5.png)

```
Stable 125308 (7245591)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)
```

**Comment by sarahkittyy** [comment]
Fixed by now
