### ISSUE TITLE
Minified React error #130 when attempting to open settings

### ISSUE THREAD

**Issue by solipsist** [sarahkittyy/KeywordTracker#58]
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
 
This is the build from this repo, downloaded today.

**Comment by sarahkittyy** [comment]
Should be fixed by now
