### ISSUE TITLE
Inbox does not appear

### ISSUE THREAD

**Issue by Kuuuube** [sarahkittyy/KeywordTracker#60]
Matches are found totally fine, it plays the notification sound and all but the inbox never appears. Previously, it would always appear after switching server once but currently it won't appear at all.

There are no errors in console and I have tested without any themes loaded.

**Comment by Ingvaarr** [comment]
same, started yesterday. Tried removing all plugins and installing discord and betterdiscord fresh and installking kwt again.

**Comment by sarahkittyy** [comment]
Fixed in v1.4.3 (5caf0a76ba0cd64d128094c87e003137f012f745)
