### ISSUE TITLE
Keywords for User ID also picking up replies

### ISSUE THREAD

**Issue by randoomdude** [sarahkittyy/KeywordTracker#64]
I wanted to use the keyword for user ID with @xxxxxxx to see messages whenever someone posts, but it also picks up whenever they are mentioned or replied too, how do you make it so it just picks up posts by that ID?

**Comment by sarahkittyy** [comment]
![image](https://github.com/sarahkittyy/KeywordTracker/assets/31551546/64d17dbc-93c8-4390-9c7e-9f206723fa5b)
Settings -> Other -> Whitelist users, just put the id in there (no @)
