### ISSUE TITLE
Enhancement - Add history

### ISSUE THREAD

**Issue by paulharman** [sarahkittyy/KeywordTracker#65]
Would be great to be able to see previous matches - sometimes I jump to a post and it doesn't quite go there or I can't see the post properly.

**Comment by sarahkittyy** [comment]
![image](https://user-images.githubusercontent.com/31551546/214435372-4aa487f0-9b2d-402b-bfce-891c01b62cc7.png)
it's right here :)

**Comment by paulharman** [comment]
@sarahkittyy but can you get it back once you click jump or mark read?

**Comment by sarahkittyy** [comment]
@paulharman If I logged every single matching message permanently I'd eat up CPU and disk space

**Comment by paulharman** [comment]
@sarahkittyy how about last 20 entries?
