### ISSUE TITLE
No longer getting notification for keywords

### ISSUE THREAD

**Issue by ImDini** [sarahkittyy/KeywordTracker#66]
The keywords are still tracked but it will not give you a normal notification or sound about it. When opening the keyword matches menu it seems to still be working apart from the 0 notifications.

**Comment by pallen0304** [comment]
*bump* Experiencing same issue, settings works but not getting notifications. DevTools shows errors in Console, I suspect this is part of the same issue as ImDini is having.
![image](https://user-images.githubusercontent.com/4258736/222834737-6b32103a-b0b5-40b4-bf1b-180076726669.png)
