### ISSUE TITLE
Opening the "notification" panel crash discord with new update

### ISSUE THREAD

**Issue by OshidaBCF** [sarahkittyy/KeywordTracker#67]
Thanks discord once again.

Now trying to open the "keyword" notification panel will crash the app.

Is there any file i should give ?

**Comment by Ingvaarr** [comment]
x2

**Comment by Ingvaarr** [comment]
working after betterdiscord update. (for me)

**Comment by OshidaBCF** [comment]
Welp it started to work again for me this morning
so i guess fixed ?
