### ISSUE TITLE
Suggestion/Fixes

### ISSUE THREAD

**Issue by badzab** [sarahkittyy/KeywordTracker#7]
- in client toast toggle
- fix ping in DND
- "work in dnd" toggle

**Comment by badzab** [comment]
suggestion: History log of all messages that were found with set keyword? and maybe, ability to jump to that message?

**Comment by Potatocrip** [comment]
Not sure if this is a problem on my end, but I've had a few instances where the notif sound plays long after a keyword is sent-- or sometimes the notif sound will just play for no reason at all.
Also, a visual notification would be cool too, like there's actually a @mention in the channel where the keyword was sent!

**Comment by sarahkittyy** [comment]
> Not sure if this is a problem on my end, but I've had a few instances where the notif sound is very delayed and plays long after a keyword is sent-- or sometimes the notif sound will just play for no reason at all.
> Also, a visual notification would be cool too, like there's actually a @mention in the channel where the keyword was sent!

I'm not sure if this is an issue on my end? The code that all notifications use is right here:
```js
this.sendMatchNotification(
  `https://cdn.discordapp.com/avatars/${message.author.id}/${message.author.avatar}.webp?size=256`,
  `User match in ${guild}!`,
  `${message.author.username} typed in #${channel.name}.`,
  `/channels/${message.guild_id}/${channel.id}/${message.id}`
);
if (this.settings.notifications) {
  Modules.SoundModule.playSound("message1", 0.4);
}
```

Nothing here would imply that there's any reason for there to be a delay between notification and sound, and so I'd bet it's a fault of the library I use to play the sound in the first place: https://github.com/rauenzi/BDPluginLibrary

**Comment by Potatocrip** [comment]
Hey so I'm dumb and I realized what caused the seemingly random/delayed pings
It's just because the keyword I added happens to be a component in some other separate words. So, like... "ring" inside of "spring" or something along those lines-- if "ring" was a keyword and "spring" was said, it'd trigger the ping. I hadn't considered that beforehand. My bad!

**Comment by sarahkittyy** [comment]
@Potatocrip Haha, it happens. You can use regex to get around that, i.e. if you want to match only the word "ring" as an individual word, you can do `/\bring\b/i` which will match two word boundaries (`\b`) around the word ring.
