### ISSUE TITLE
Notification Sound not working.

### ISSUE THREAD

**Issue by PadreJesus** [sarahkittyy/KeywordTracker#71]
From some updates from Discord or BetterDiscord, the notification sound stopped working when is triggered by the words.

**Comment by desperateforexports** [comment]
Seconding this! Previously, I was even able to customize which specific notification sound would play when a match was found, but this no longer works, and the plugin seems to follow global Discord notification settings (i.e. not pinging/playing a sound when set to DND)

**Comment by Caysonting** [comment]
@sarahkittyy @infernix @SoftwareSing please help, without sound, we can't even know if there is new detected keyword. Thanks!
