### ISSUE TITLE
Enhancement Request: Option to keep jump'ed messages in notification menu

### ISSUE THREAD

**Issue by paulharman** [sarahkittyy/KeywordTracker#72]
Sometimes jump doesn't correctly load the right message.  I'd like to have the option to keep messages I've jumped to in the notification panel until I manually mark them as read.  Alternatively, a history would work too.

**Comment by sarahkittyy** [comment]
Added in v1.5.0 [f9f6de4](https://github.com/sarahkittyy/KeywordTracker/commit/f9f6de4f6b1727c9586b84e6fece91845f1d5a97)
