### ISSUE TITLE
KeywordTracker plugin freezing BD

### ISSUE THREAD

**Issue by PadreJesus** [sarahkittyy/KeywordTracker#79]
After some Discord updates, with an old config of keyword track, it have been freezing the whole Discord and reporting errors.
So I reinstalled the plugin and deleted the config file.

Still reporting this:
[2023-11-08 17:16:26.626][CONSOLE:ERROR] [KeywordTracker] TypeError: Cannot read properties of undefined (reading 'filter')

**Comment by sarahkittyy** [comment]
I released an update here. BD hasn't yet pushed that update onto their site. If you want, you can just directly download the plugin.js file from this repo and use it.
