### ISSUE TITLE
Keyword Matches not working anymore

### ISSUE THREAD

**Issue by LeBaguette75** [sarahkittyy/KeywordTracker#87]
Hi, when i click on Keyword Matches, nothing happens (there should be a list of all matched keywords). That was working fine yesterday... Thanks in advance !

**Comment by SaiyanOfDarkness** [comment]
Just to add on to this.  I still hear the sound indicator like I get a keyword match, however the button located near search no longer brings up the window.  This happened to me after I updated the BDFDB library plugin from DevilBro

**Comment by sarahkittyy** [comment]
workin on it ^-^

**Comment by dimzachar** [comment]
and I thought I was doing something wrong

**Comment by TheGameKnave** [comment]
> workin on it ^-^

Can't wait! I keep hearing the blip but not knowing whereeee! :)

**Comment by sarahkittyy** [comment]
fixed in latest patch
