### ISSUE TITLE
[Enhancement] Custom notification sound

### ISSUE THREAD

**Issue by mkcoldwolf** [sarahkittyy/KeywordTracker#9]
Would be great if we can define different sound for different word tracked

**Comment by sarahkittyy** [comment]
I'm not sure how I'd implement this, there's only a few different sounds discord's sound module can produce at all, so I'll take a look, but I can't promise this will be a feature anytime soon.

**Comment by mkcoldwolf** [comment]
> I'm not sure how I'd implement this, there's only a few different sounds discord's sound module can produce at all, so I'll take a look, but I can't promise this will be a feature anytime soon.

I think we can hook into the notification sound plugin which is written by @mwittrien
https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/NotificationSounds
Which he defined 6 types of notification sounds which can be customized by users
![image](https://user-images.githubusercontent.com/32544898/129972227-64775529-db68-40ab-9dd1-7cf6daebb576.png)

As I really need a notification sound, i've written one my self real quick lol, we can simply let user choose which type of sounds from NotificationSounds they want, and then play it with
`BdApi.Plugins.get("NotificationSounds").instance.playAudio("dm");` easily

**Comment by sarahkittyy** [comment]
I think there was someone using that plugin, I actually just came in to send it here but I guess you beat me to it. Though obviously I don't want to make NotificationSounds a dependency, I could definitely make it compatible in the future.

**Comment by mkcoldwolf** [comment]
> I think there was someone using that plugin, I actually just came in to send it here but I guess you beat me to it. Though obviously I don't want to make NotificationSounds a dependency, I could definitely make it compatible in the future.

Yes. completely agreed, just make a an compatible option, but not a necessary dependency xd
