### ISSUE TITLE
Could not open settings for keywordtracker

### ISSUE THREAD

**Issue by AttyRyu** [sarahkittyy/KeywordTracker#90]
stable 328697 (38204c9) 
Host 1.0.9163 x64 (52153) 
Build Override: N/A 
Windows 10 64-bit (10.0.19045)

KeywordTrackerv1.5.4by sawahkitty!~<3

ZeresPluginLibraryv2.0.22by Zerebos

![image](https://github.com/user-attachments/assets/a7e00d26-c26b-45e1-a771-fee07303f6af)

![image](https://github.com/user-attachments/assets/c2bbfacf-f9c0-4d21-9c23-303f6128dcb1)

![image](https://github.com/user-attachments/assets/00fcfe06-accf-4391-9482-b51d1c69e51c)

I've been using keywordtracker plugin of betterdiscord for a few months but after restarting my PC and opening discord again, this error begun occurring - "Could not open settings for Keywordtracker" appears when I try to click on the "Settings" button (gear icon) under Keywordtracker plugin. 

I see that my issue seems similar to this https://github.com/sarahkittyy/KeywordTracker/issues/77 but this was an old issue that has already been resolved so would probably be a different scenario. Also, I cannot figure out how to access the error logging that is present in that issue.

Could this have something to do with a discord or betterdiscord update? As this only started happening when I closed and reopened discord.

Please look into this.

**Comment by AttyRyu** [comment]
Okay, I was able to get the console log for this when trying to open:

4web.899d1a61a53961491368.js:12 [Addon Settings] Unable to get settings panel for KeywordTracker. TypeError: Modules.GuildStore.getGuilds is not a function
    at KeywordTracker.buildSettings (KeywordTracker.plugin.js:962:52)
    at KeywordTracker.getSettingsPanel (KeywordTracker.plugin.js:786:16)
    at renderer.js:5:92654
    at Object.ek (web.899d1a61a53961491368.js:12:944573)
    at eY (web.899d1a61a53961491368.js:12:944727)
    at web.899d1a61a53961491368.js:12:963036
    at re (web.899d1a61a53961491368.js:12:963135)
    at rt (web.899d1a61a53961491368.js:12:963549)
    at web.899d1a61a53961491368.js:12:969011
    at oD (web.899d1a61a53961491368.js:12:1026084)
    at eU (web.899d1a61a53961491368.js:12:943711)
    at ro (web.899d1a61a53961491368.js:12:964840)
    at tk (web.899d1a61a53961491368.js:12:950508)
    at tx (web.899d1a61a53961491368.js:12:950292)

**Comment by Lexiconmancer** [comment]
Same issue. I'm noting a lot of the stuff relates to guilds, which I do not have access to. Currently watching for where it throws up the errors and trying to comment out those lines. If it works, then probably sometime tomorrow I'll post the code that repaired it for me. If not, will try to remember to post that I was unsuccessful. Would appreciate if anyone else looking at this can share info. I am an amateur.

**Comment by sarahkittyy** [comment]
Fixed in v1.5.5
